config/routes.rb
FirstProject::Application.routes.draw do
  resources :multi_boards

  resources :boards

  resources :images

  resources :users

  root :to => 'images#index'

end

app/models/multi_board.rb
class MultiBoard < ActiveRecord::Base
  attr_accessible :link
  has_many :users
  has_many :images
end

app/controllers/multi_boards_controller.rb
class MultiBoardsController < ApplicationController
  # GET /multi_boards
  # GET /multi_boards.json
  def index
    @multi_boards = MultiBoard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @multi_boards }
    end
  end

  # GET /multi_boards/1
  # GET /multi_boards/1.json
  def show
    @multi_board = MultiBoard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @multi_board }
    end
  end

  # GET /multi_boards/new
  # GET /multi_boards/new.json
  def new
    @multi_board = MultiBoard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @multi_board }
    end
  end

  # GET /multi_boards/1/edit
  def edit
    @multi_board = MultiBoard.find(params[:id])
  end

  # POST /multi_boards
  # POST /multi_boards.json
  def create
    @multi_board = MultiBoard.new(params[:multi_board])

    respond_to do |format|
      if @multi_board.save
        format.html { redirect_to @multi_board, notice: 'Multi board was successfully created.' }
        format.json { render json: @multi_board, status: :created, location: @multi_board }
      else
        format.html { render action: "new" }
        format.json { render json: @multi_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /multi_boards/1
  # PUT /multi_boards/1.json
  def update
    @multi_board = MultiBoard.find(params[:id])

    respond_to do |format|
      if @multi_board.update_attributes(params[:multi_board])
        format.html { redirect_to @multi_board, notice: 'Multi board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @multi_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /multi_boards/1
  # DELETE /multi_boards/1.json
  def destroy
    @multi_board = MultiBoard.find(params[:id])
    @multi_board.destroy

    respond_to do |format|
      format.html { redirect_to multi_boards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/multi_boards_helper.rb
module MultiBoardsHelper
end

app/views/multi_boards/_form.html.erb
<%= form_for(@multi_board) do |f| %>
  <% if @multi_board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@multi_board.errors.count, "error") %> prohibited this multi_board from being saved:</h2>

      <ul>
      <% @multi_board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/multi_boards/edit.html.erb
<h1>Editing multi_board</h1>

<%= render 'form' %>

<%= link_to 'Show', @multi_board %> |
<%= link_to 'Back', multi_boards_path %>

app/views/multi_boards/index.html.erb
<h1>Listing multi_boards</h1>

<table>
  <tr>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @multi_boards.each do |multi_board| %>
  <tr>
    <td><%= multi_board.link %></td>
    <td><%= link_to 'Show', multi_board %></td>
    <td><%= link_to 'Edit', edit_multi_board_path(multi_board) %></td>
    <td><%= link_to 'Destroy', multi_board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Multi board', new_multi_board_path %>

app/views/multi_boards/new.html.erb
<h1>New multi_board</h1>

<%= render 'form' %>

<%= link_to 'Back', multi_boards_path %>

app/views/multi_boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= @multi_board.link %>
</p>


<%= link_to 'Edit', edit_multi_board_path(@multi_board) %> |
<%= link_to 'Back', multi_boards_path %>