config/routes.rb
FirstProject::Application.routes.draw do
  resources :multi_boards

  resources :boards

  resources :images

  resources :users

  root :to => 'images#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :link
  has_one :user
  has_many :boards
  has_many :multi_boards

  	def self.search(name)

# create a client object with your app credentials
	client = Flickr.new(:client_id => 'f4e398d71445be2bf1eac20a932e6768')

	images = client.get('/image', :q => name)

	images
	end
end

 # http://api.flickr.com/services/feeds/photos_public.gne?tags=cat&tagmode=any&format=json&jsoncallback=?

 # json_hash = JSON.parse(File.open('json_example.json').read)

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  include AWS::S3
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])
    @formatted_image = MiniMagick::Image.open("#{@image.link}")
    @formatted_image.sketch 15
    #FileUtils.mkdir_p "public/images/#{@image.id}"
    #@formatted_image.write "public/images/#{@image.id}/my_test.jpg"
    S3Object.store "#{@image.id}/my_test1.jpg", @formatted_image.to_blob, "BadArt"
    @formatted_image = MiniMagick::Image.open("#{@image.link}")
    @formatted_image.charcoal 0
    S3Object.store "#{@image.id}/my_test2.jpg", @formatted_image.to_blob, "BadArt"
    @formatted_image = MiniMagick::Image.open("#{@image.link}")
    @formatted_image.emboss 2
    S3Object.store "#{@image.id}/my_test3.jpg", @formatted_image.to_blob, "BadArt"
    @formatted_image = MiniMagick::Image.open("#{@image.link}")
    @formatted_image.normalize
    S3Object.store "#{@image.id}/my_test4.jpg", @formatted_image.to_blob, "BadArt"
    @formatted_image = MiniMagick::Image.open("#{@image.link}")
    @formatted_image.implode -3
    S3Object.store "#{@image.id}/my_test5.jpg", @formatted_image.to_blob, "BadArt"
    @formatted_image = MiniMagick::Image.open("#{@image.link}")
    @formatted_image.monochrome
    S3Object.store "#{@image.id}/my_test6.jpg", @formatted_image.to_blob, "BadArt"
    @formatted_image = MiniMagick::Image.open("#{@image.link}")
    @formatted_image.solarize(threshold=50)
    S3Object.store "#{@image.id}/my_test7.jpg", @formatted_image.to_blob, "BadArt"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Bad Art</h1>

<div id="columns">
<% @images.each do |image| %>
   <div class="pin">
    <%= image_tag image.link %>
    <p> <%= link_to 'Make it Bad', image %> </p>
    </div>
<% end %>
</div>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<div class=images>
  <h1>Your Bad Art</h1>
  <%= image_tag @image.link %>
<% (1..7).each do |i| %>  
<%= image_tag AWS::S3::S3Object.url_for("#{@image.id}/my_test#{i}.jpg", "BadArt")%>
<% end %>

<%= link_to 'Back', images_path %>
</div>